---
title: "Appunti di geostatistica"
subtitle: "Recap Modulo 2"
author: "Massimo Bressan, ARPAV UQA"
date: "today"

format: 
  html:
    self-contained: true
    fig-width: 8
    fig-height: 4
    code-fold: false
---

# Leggimi

L'obiettivo degli appunti è ricapitolare i passaggi fondamentali di calcolo in R relativi all'esercitazione pratica sui metodi di interpolazione di tipo deterministico e geostatistico, svolti nel corso di formazione ARPAV tenuto dal Prof. Pirotti (UniPD) nel 2024 (per 16 ore complessive).

Strategia generale di analisi dei dati:

- creo un "dataset incompleto" di "punti" di misura della temperatura e della quota altimetrica a partire dal "dataset completo" fornito dal "raster" della Regione Veneto;

- utilizzo metodi alternativi di interpolazione, sia di tipo deterministico che geostatistico, per ricreare una stima il più possibile attendibile del "dataset completo" (raster) a partire dal "dataset incompleto" (punti);

- verifico i risultati di interpolazione effettuato a partire dai punti "noti" sui punti "non noti".

In altri termini, l'esercizio ripropone la classica situazione operativa in cui a partire da alcune limitate osservazioni sperimentali (punti di campionamento) di variabili ambientali si ha la necessità di riprodurre una stima il più possibile attendibile del "campo continuo" (in termini geografici - ed eventualmente temporali) delle variabili di interesse.

Nota bene:

Per tutte le spiegazioni di carattere teorico ed applicativo si rimanda al [materiale didattico](https://github.com/fpirotti/ARPA2024_corsoBase){.external target="_blank"} reso disponibile dal Prof. Pirotti (UniPd).

L'obiettivo dell'esercizio è ripercorrere a futura memoria e nel modo più sintetico possibile, i vari passaggi di calcolo in R, senza introdurre alcun tipo di valutazione critica e/o ulteriore discussione, sia rispetto ai metodi sia rispetto ai risultati ottenuti.

L'unica variazione rispetto agli scripts originali del Prof. Pirotti (UniPD) è rappresentata dall'applicazione di metodi leggermente differenti per il kriging (funzioni ed argomenti dal pacchetto 'gstat') che portano comunque a risultati finali del tutto sovrapponibili.

# *cfr. file:*<br> what_is_kriging_in_a_nutshell.html

Brevissima nota (10 min di lettura) che sintetizza le principali caratteristiche tecniche dell'interpolazione spaziale tramite kriging. 

In particolare, viene evidenziato il significato e l'impiego del "variogramma" finalizzato al calcolo dei pesi relativi al sistema lineare di kriging.


# *cfr. file:*<br> 00_my_recap_data_cleaning_and_munging.R

A partire dai dati grezzi:

- raster DEM RV
- raster temperatura RV

applicazione di alcune operazioni preliminari per definire un dataset “pulito” su cui svolgere gli esercizi, in particolare:

- importazione raster (temperatura, DEM);
- campionamento di 1000 punti su raster temperatura;
- estrazione delle quote altimetriche in corrispondenza dei punti già campionati per la temperatura;
- creazione dataframe con coordinate (xy), temperatura e quota.

# *cfr. file:*<br> 01_my_recap_interpolation_deterministic_methods.R

Applicazione dei metodi di interpolazione di tipo deterministico:

- nearest neighbour;
- nearest neighbour with linear interpolation;
- idw: inverse distance weighted power 1;
- idw: inverse distance weighted power 2;

e verifica finale dell'accuratezza di stima.

# *cfr. file:*<br> 02_my_recap_interpolation_geostatistics_methods_ok_uk_ked_ck.R

Applicazione dei metodi di interpolazione di tipo geostatistico:

- ordinary kriging;
- universal kriging;
- kriging with external drift;
- co-kriging;

e verifica finale dell'accuratezza di stima.


# Conclusioni

La valutazione critica dei risultati e dei metodi di analisi viene lasciata come esercizio individuale di approfondimento.

